theme: minima
google_fonts:
  - Inter
header_pages:
  - index.md
  - about.md
  - momentum.md
  - prototype-releases.md
  - pathsofdestiny.md
  - lablog.md
sass:
  style: compressed

include:
  - assets/css/custom.css

