title: F. Günışığı Aydoğan | Independent Researcher in Cognitive Systems & AI | Computer Programming Student
author: F. Günışığı Aydoğan
description: Independent Researcher in Cognitive Systems & AI
markdown: kramdown
theme: minima
