title: F. Günışığı Aydoğan | Independent Researcher in Cognitive Systems & AI | Computer Programming Student
description: My projects, thoughts, and experiments
theme: minima

markdown: kramdown
kramdown:
  input: GFM

# Remove these if present:
# plugins:
#   - jekyll-feed

header_pages:
  - index.md
  - momentum.md
  - prototypes.md
  - releases.md
  - paths-of-destiny.md
  - lablog.md
  - about.md
  - contact.md

footer_pages:
  - about.md
  - contact.md

social_links:
  linkedin: gunisigiaydogan
  github: morevna6
