theme: minima

header_pages:
  - index.md
  - about.md
  - momentum.md
  - prototype-releases.md
  - pathsofdestiny.md
  - lablog.md

sass:
  style: compressed

google_fonts:
  - Inter

include:
  - assets/css
